
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRE5IK0RwUDQxczR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeE1EVXdNVE15TURKYUZ3MHpOVEV4TURNd01UTTNNREphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURTSjF0SEV4ZjduWUpvTjNkczVGQkFSNk5EZEw2VXBGUmxsRERYRzRYbFJhei9ld3FKOWpIbUhoNW0KSUJpMVBIS2JpbTRjMUFSRkpkTHB6NlRxT2tDOWpmYU45cCtEWUx1K2hIZjV4U0JZd2EweE83azNXei9FcE5HOAo2T0Z3WkxqazBqSG9QcnJjNHVuaVZvTWlCekRHanVhV0w3dSs5a01tejRydXVWaThtRWgvemZUSlpCNnRMNGo0CnZhSU03L2ZHTjdkSk13ZE9rb2xBL3h0eFJoNkljdmJhN0E3M3pzWlZscmFFQktiMWR0UXdjaDIxd2FBaVl0MXIKS3FHb1RqMXJ3bkhlUkE5ZUVjY29RcU1vY2Z2MTh0dzZzQmo0Rm92RnNRdjZFVngyajZXdmRSaWt4cVBZY1FEOApmZVhhcis2eS9ZNUdxMWwzRmRhUy80Z3gyM0pwQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUT0dYMlB5MGFpYTJJZHZENkJSZlJsSGJybDlqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQmc3RVVoV0RFOApmaFR0YUV6azNWUWc1cjhnMGRiTWZSREpCN3FtZHh3UWhhdEhReXJxdjI1WWFvZ0s1NFVyajF4ZzEzRG9IMk91ClF6SzQ0QkQ1RmR0MHVpUkRjVy82Wk5Bd1RYQ3paVkV4ZmYySjBoblFTNmwrTC9tYkVTbU1UUGRJNWZiNE16SU8KTlBIMEZUcHpPcTdjRnQ4bWVsbis1MFRTWUw5LzcvaFEyMnE5NmhwT29BWnA1L0EyelZzbW5OQUpmM24vMmxSbgoxMEFRV2F4NU43bXF6MTVWaEZtTEQwVmZPSlhEV1JWdytoMGR6MUF4RzBxNnRaUkRSWWVHMXBMbmxpTGlwY1dTCmEwVlNNYTlDVXhDRExrd2dIbk9FRjg5OWVmSDYrcnZuQUw0MkJ0VVR5WEpIQ1h3WnVMTy93bTNBblh4QUhSWHQKSnRDL0VVaXdWekM5Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://a66b8de1-ab7a-4318-920f-47600d01fa67.us-east-2-gw.linodelke.net:443
  name: lke530638

users:
- name: lke530638-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Im1XZVFWRHBRNEpPaGRoOUs5cUU0Tnp0eGs2Y2dINC1kTWk0dGNTS0dSUU0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tazJ3N2giLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiM2NiMzlkYmYtZjExNi00YThhLWJiZTYtODc2MDRmN2E1YWJhIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.PajVDIQ3Wt0NrRtDe0d53SLut4-LYvA6_MBrtThg4XxsYs2DCoPUWMRQIrZM1L02v_SwD7gnlFPvGeFKvUKcF2XxOpj07ty6OWxyI1ZX2oq2pQR74Wtr2mLLd-DdA5hBHzx7bKhHhcRuYMF8L0sANUft1TfFkf20y8hRamaY2VFuSdFTXHDb_D25OSp0w6NNW5BK3yZBWV4L8hKykRDh-ZqdsAICCjYSmyFCacoFshNHSjbItiadbMLUACyyhIBjtFjfiYx_cof1d9klSV29cWlSVvzQUMIlI5ReUJKbuI0PV3n6aYZ4S6yPtMBmDvIXXSZC_7EKf2za_YCRVBmbzg

contexts:
- context:
    cluster: lke530638
    namespace: default
    user: lke530638-admin
  name: lke530638-ctx

current-context: lke530638-ctx
